name: "py-docker-starter"
description: "Boilerplate for GH-Action with Python in docker."
author: 'sajith-rahim'
branding:
  icon: 'command-palette' # Reference https://primer.style/octicons/
  color: 'blue' # color in lowercase.
inputs:
  fname:
    description: "input to docker action : file name"
    required: true
outputs:
  response-text:
    description: "output text from docker action"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - '${{ inputs.fname }}'
