name: "py-docker-starter"
description: "Boilerplate for GH-Action with Python in docker."
author: 'sajith-rahim'
branding:
  icon: 'command-palette' # Reference https://primer.style/octicons/
  color: 'blue' # color in lowercase.
inputs:
  fname:
    description: "file name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - '${{ inputs.fname }}'
