name: Sample py-docker gh-action

on:
  workflow_dispatch

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: run-docker-action
      id: run-docker-action
      uses: ./
      with:
        fname: 'data'

    - name: show-output
      run: |
        echo "Response Text: ${{ steps.run-docker-action.outputs.response-text }}"
    
