name: Sample py-docker gh-action

on:
  workflow_dispatch
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: run-docker
      uses: ./
      with:
        fname: 'user'
    
    - name: run-extract
      uses: shrink/actions-docker-extract@v2
      id: extract
      with:
        image: my-example-image
        path: /app/.
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: dist
